export {
  TEST_ID,
  adminMasterCardTestId,
  bookingRowTestId,
  bookingStatusTestId,
  catalogCategoryTestId,
  catalogDistrictTestId,
  masterCardTestId,
  onboardingPresetTestId,
  onboardingProgressTestId,
  onboardingStepTestId,
  onboardingTemplateTestId,
  reviewStarTestId,
  serviceOptionTestId,
  slotChipTestId,
  portfolioCardTestId,
  portfolioSetCoverTestId,
  portfolioRemoveTestId,
  publicPortfolioShotTestId,
} from '../src/shared/lib/test-id'
