/**
 * Фронт матчится по `code`, а не по HTTP-статусу или тексту сообщения.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  SLOT_TAKEN: 'SLOT_TAKEN',
  TIME_OVERLAP: 'TIME_OVERLAP',
  INVALID_STATE: 'INVALID_STATE',
  HOLD_EXPIRED: 'HOLD_EXPIRED',
  LEAD_TIME_VIOLATION: 'LEAD_TIME_VIOLATION',
  CANCEL_CUTOFF_PASSED: 'CANCEL_CUTOFF_PASSED',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SLOT_TAKEN: 409,
  TIME_OVERLAP: 409,
  INVALID_STATE: 409,
  HOLD_EXPIRED: 410,
  LEAD_TIME_VIOLATION: 422,
  CANCEL_CUTOFF_PASSED: 422,
  LIMIT_EXCEEDED: 422,
  RATE_LIMITED: 429,
  INTERNAL: 500,
}
