import {
  ADMIN_EMAIL,
  ANNA_SLUG,
  BORIS_SLUG,
  CLIENT_EMAIL,
  CLIENT_OTHER_EMAIL,
  DRAFT_MASTER_EMAIL,
  KATYA_SLUG,
  MASTER_EMAIL,
  PASSWORD,
} from '../accounts'
import {
  ADMIN_ID,
  CATEGORY_BROWS_ID,
  CATEGORY_NAILS_ID,
  CLIENT_ID,
  CLIENT_OTHER_ID,
  COMPLETED_BOOKING_ID,
  CONFIRMED_BOOKING_ID,
  DISTRICT_FRUNZE_ID,
  DISTRICT_MOSCOW_ID,
  DRAFT_MASTER_PROFILE_ID,
  DRAFT_MASTER_USER_ID,
  FOREIGN_BOOKING_ID,
  LOCATION_ID,
  MASTER_PROFILE_ID,
  MASTER_USER_ID,
  PENDING_BOOKING_ID,
  PENDING_MASTER_PROFILE_ID,
  SECOND_LOCATION_ID,
  SECOND_MASTER_PROFILE_ID,
  SECOND_SERVICE_ID,
  SERVICE_ID,
  SLOT_10_ID,
  SLOT_11_ID,
  SLOT_14_ID,
  SLOT_15_ID,
} from '../ids'
import { addDaysYmd, slotIso, todayYmd } from '../time'
import type { E2eBooking, E2eUser, MockWorld } from './types'

function user(input: E2eUser): E2eUser {
  return input
}

function bookingAt(hour: number, extra: Partial<E2eBooking> & Pick<E2eBooking, 'id' | 'status' | 'clientUserId' | 'clientName'>): E2eBooking {
  const today = todayYmd()
  const range = slotIso(today, hour)

  return {
    masterId: MASTER_PROFILE_ID,
    masterUserId: MASTER_USER_ID,
    masterDisplayName: 'Анна Ногтева',
    serviceId: SERVICE_ID,
    serviceTitle: 'Маникюр комбинированный',
    serviceDurationMin: 90,
    priceAmount: '60',
    currency: 'BYN',
    startsAt: range.startsAt,
    endsAt: range.endsAt,
    holdExpiresAt: null,
    clientComment: null,
    confirmedAt: extra.status === 'confirmed' || extra.status === 'completed' ? range.startsAt : null,
    completedAt: extra.status === 'completed' ? new Date().toISOString() : null,
    masterNote: extra.status === 'pending' ? 'аллергия на гель' : null,
    clientPhone: '+375291112233',
    addressHint: 'Фрунзенский, ориентир ТЦ',
    addressExact: 'ул. Притыцкого 29, каб. 3',
    review: extra.status === 'completed' ? null : null,
    clientReview: null,
    ...extra,
  }
}

export function createWorld(): MockWorld {
  const today = todayYmd()
  const slot10 = slotIso(today, 10)
  const slot11 = slotIso(today, 11)
  const slot14 = slotIso(today, 14)
  const slot15 = slotIso(today, 15)
  const completedRange = slotIso(addDaysYmd(today, -2), 12)

  return {
    users: [
      user({
        id: CLIENT_ID,
        email: CLIENT_EMAIL,
        password: PASSWORD,
        firstName: 'Оля',
        lastName: null,
        role: 'client',
        emailVerified: true,
        telegramLinked: false,
        profileStatus: null,
        onboardingStep: null,
      }),
      user({
        id: CLIENT_OTHER_ID,
        email: CLIENT_OTHER_EMAIL,
        password: PASSWORD,
        firstName: 'Кира',
        lastName: null,
        role: 'client',
        emailVerified: true,
        telegramLinked: false,
        profileStatus: null,
        onboardingStep: null,
      }),
      user({
        id: MASTER_USER_ID,
        email: MASTER_EMAIL,
        password: PASSWORD,
        firstName: 'Анна',
        lastName: null,
        role: 'master',
        emailVerified: true,
        telegramLinked: false,
        profileStatus: 'published',
        onboardingStep: 'done',
      }),
      user({
        id: DRAFT_MASTER_USER_ID,
        email: DRAFT_MASTER_EMAIL,
        password: PASSWORD,
        firstName: 'Новый',
        lastName: null,
        role: 'master',
        emailVerified: false,
        telegramLinked: false,
        profileStatus: 'draft',
        onboardingStep: 'profile',
      }),
      user({
        id: ADMIN_ID,
        email: ADMIN_EMAIL,
        password: PASSWORD,
        firstName: 'Админ',
        lastName: null,
        role: 'admin',
        emailVerified: true,
        telegramLinked: false,
        profileStatus: null,
        onboardingStep: null,
      }),
    ],
    resetTokens: new Map(),
    favorites: new Set(),
    districts: [
      {
        id: DISTRICT_FRUNZE_ID,
        name: 'Фрунзенский',
        slug: 'frunzenskiy',
        city: 'Минск',
      },
      {
        id: DISTRICT_MOSCOW_ID,
        name: 'Московский',
        slug: 'moskovskiy',
        city: 'Минск',
      },
    ],
    categories: [
      {
        id: CATEGORY_NAILS_ID,
        name: 'Ногти',
        slug: 'nogti',
        icon: null,
        sort: 1,
        parentId: null,
      },
      {
        id: CATEGORY_BROWS_ID,
        name: 'Брови',
        slug: 'brovi',
        icon: null,
        sort: 2,
        parentId: null,
      },
    ],
    templates: [
      {
        categorySlug: 'nogti',
        title: 'Маникюр комбинированный',
        durationMin: 90,
        price: 60,
        priceType: 'fixed',
      },
      {
        categorySlug: 'brovi',
        title: 'Коррекция бровей',
        durationMin: 45,
        price: 40,
        priceType: 'fixed',
      },
    ],
    catalog: [
      {
        id: MASTER_PROFILE_ID,
        slug: ANNA_SLUG,
        displayName: 'Анна Ногтева',
        headline: 'Мастер маникюра, 5 лет',
        districtName: 'Фрунзенский',
        districtSlug: 'frunzenskiy',
        ratingAvg: 4.8,
        ratingCount: 12,
        priceFrom: 60,
        specialty: 'Маникюр комбинированный',
      },
      {
        id: SECOND_MASTER_PROFILE_ID,
        slug: BORIS_SLUG,
        displayName: 'Борис Бровист',
        headline: 'Брови и ресницы',
        districtName: 'Московский',
        districtSlug: 'moskovskiy',
        ratingAvg: 4.2,
        ratingCount: 4,
        priceFrom: 90,
        specialty: 'Коррекция бровей',
      },
    ],
    publicMasters: [
      {
        id: MASTER_PROFILE_ID,
        slug: ANNA_SLUG,
        displayName: 'Анна Ногтева',
        headline: 'Мастер маникюра, 5 лет',
        bio: 'Аккуратный комбинированный маникюр.',
        status: 'published',
        experienceSince: 2019,
        languages: ['ru'],
        primaryLocation: {
          id: LOCATION_ID,
          districtId: DISTRICT_FRUNZE_ID,
          districtName: 'Фрунзенский',
          districtSlug: 'frunzenskiy',
          type: 'salon',
          addressHint: 'Фрунзенский, ориентир ТЦ',
          isPrimary: true,
        },
        ratingAvg: 4.8,
        ratingCount: 12,
        contact: {
          publicPhone: '+375291000001',
          instagram: 'anna.nails',
          telegramUsername: 'anna_nails',
          website: null,
        },
        services: [
          {
            id: SERVICE_ID,
            categoryName: 'Ногти',
            categorySlug: 'nogti',
            title: 'Маникюр комбинированный',
            description: 'Снятие, маникюр, покрытие',
            durationMin: 90,
            price: 60,
            priceMax: null,
            priceType: 'fixed',
            currency: 'BYN',
          },
        ],
        portfolio: [],
      },
      {
        id: SECOND_MASTER_PROFILE_ID,
        slug: BORIS_SLUG,
        displayName: 'Борис Бровист',
        headline: 'Брови и ресницы',
        bio: null,
        status: 'published',
        experienceSince: 2021,
        languages: ['ru'],
        primaryLocation: {
          id: SECOND_LOCATION_ID,
          districtId: DISTRICT_MOSCOW_ID,
          districtName: 'Московский',
          districtSlug: 'moskovskiy',
          type: 'home_studio',
          addressHint: 'Московский район',
          isPrimary: true,
        },
        ratingAvg: 4.2,
        ratingCount: 4,
        contact: null,
        services: [
          {
            id: SECOND_SERVICE_ID,
            categoryName: 'Брови',
            categorySlug: 'brovi',
            title: 'Коррекция бровей',
            description: null,
            durationMin: 45,
            price: 90,
            priceMax: null,
            priceType: 'fixed',
            currency: 'BYN',
          },
        ],
        portfolio: [],
      },
    ],
    publicReviews: [
      {
        id: 'cccccccc-cccc-4ccc-8ccc-ccccccccccc1',
        rating: 5,
        text: 'Очень аккуратно, буду возвращаться.',
        createdAt: new Date().toISOString(),
        clientFirstName: 'Маша',
        serviceTitle: 'Маникюр комбинированный',
        masterReply: null,
        repliedAt: null,
        verified: true,
      },
    ],
    profiles: [
      {
        id: MASTER_PROFILE_ID,
        slug: ANNA_SLUG,
        displayName: 'Анна Ногтева',
        headline: 'Мастер маникюра, 5 лет',
        bio: 'Аккуратный комбинированный маникюр.',
        status: 'published',
        experienceSince: 2019,
        languages: ['ru'],
        primaryLocation: {
          id: LOCATION_ID,
          districtId: DISTRICT_FRUNZE_ID,
          districtName: 'Фрунзенский',
          districtSlug: 'frunzenskiy',
          type: 'salon',
          addressHint: 'Фрунзенский, ориентир ТЦ',
          isPrimary: true,
        },
        contact: {
          publicPhone: '+375291000001',
          instagram: 'anna.nails',
          telegramUsername: 'anna_nails',
          website: null,
        },
      },
      {
        id: DRAFT_MASTER_PROFILE_ID,
        slug: 'novyy-master',
        displayName: '',
        headline: null,
        bio: null,
        status: 'draft',
        experienceSince: null,
        languages: null,
        primaryLocation: null,
        contact: null,
      },
    ],
    services: [
      {
        id: SERVICE_ID,
        categoryId: CATEGORY_NAILS_ID,
        categoryName: 'Ногти',
        categorySlug: 'nogti',
        title: 'Маникюр комбинированный',
        description: 'Снятие, маникюр, покрытие',
        durationMin: 90,
        bufferAfterMin: 0,
        price: 60,
        priceMax: null,
        priceType: 'fixed',
        currency: 'BYN',
        isActive: true,
        sort: 0,
      },
    ],
    availability: [
      { ...slot10, slotIds: [SLOT_10_ID], extraPayAmount: null },
      { ...slot11, slotIds: [SLOT_11_ID], extraPayAmount: null },
      { ...slot14, slotIds: [SLOT_14_ID], extraPayAmount: null },
      { ...slot15, slotIds: [SLOT_15_ID], extraPayAmount: null },
    ],
    conflictStartsAt: slot15.startsAt,
    calendarSlots: [
      {
        id: SLOT_10_ID,
        ...slot10,
        status: 'open',
        clientName: null,
        bookingId: null,
        isExtra: false,
        extraPayAmount: null,
      },
      {
        id: SLOT_11_ID,
        ...slot11,
        status: 'open',
        clientName: null,
        bookingId: null,
        isExtra: false,
        extraPayAmount: null,
      },
      {
        id: SLOT_14_ID,
        ...slot14,
        status: 'open',
        clientName: null,
        bookingId: null,
        isExtra: false,
        extraPayAmount: null,
      },
    ],
    blocks: [],
    exceptions: [],
    bookings: [
      bookingAt(16, {
        id: PENDING_BOOKING_ID,
        status: 'pending',
        clientUserId: CLIENT_ID,
        clientName: 'Оля',
        clientComment: 'хочу короткую длину',
      }),
      bookingAt(17, {
        id: CONFIRMED_BOOKING_ID,
        status: 'confirmed',
        clientUserId: CLIENT_ID,
        clientName: 'Оля',
      }),
      {
        ...bookingAt(12, {
          id: COMPLETED_BOOKING_ID,
          status: 'completed',
          clientUserId: CLIENT_ID,
          clientName: 'Оля',
        }),
        startsAt: completedRange.startsAt,
        endsAt: completedRange.endsAt,
        completedAt: completedRange.endsAt,
        confirmedAt: completedRange.startsAt,
      },
      bookingAt(18, {
        id: FOREIGN_BOOKING_ID,
        status: 'confirmed',
        clientUserId: CLIENT_OTHER_ID,
        clientName: 'Кира',
      }),
    ],
    portfolioItems: [],
    ledgerCategories: [
      { id: 'c-service', masterId: MASTER_PROFILE_ID, kind: 'income', name: 'Услуги', slug: 'service', isSystem: true },
      { id: 'c-tip', masterId: MASTER_PROFILE_ID, kind: 'income', name: 'Чаевые', slug: 'tip', isSystem: true },
      { id: 'c-materials', masterId: MASTER_PROFILE_ID, kind: 'expense', name: 'Материалы', slug: 'materials', isSystem: true },
      { id: 'c-rent', masterId: MASTER_PROFILE_ID, kind: 'expense', name: 'Аренда', slug: 'rent', isSystem: true },
      { id: 'c-other', masterId: MASTER_PROFILE_ID, kind: 'expense', name: 'Прочее', slug: 'other', isSystem: true },
    ],
    ledgerEntries: [],
    adminMasters: [
      {
        id: PENDING_MASTER_PROFILE_ID,
        slug: KATYA_SLUG,
        displayName: 'Катя на проверке',
        status: 'pending_review',
        districtName: 'Фрунзенский',
        updatedAt: new Date().toISOString(),
      },
    ],
    idempotency: new Map(),
  }
}
